const RETAILER_DEFINITIONS = [
  {
    retailerKey: 'adeg',
    retailerName: 'Adeg',
    channel: 'aggregator',
    label: 'Aktionsfinder ADEG Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/adeg/',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder meldet aktuell fuer ADEG keine oeffentlich extrahierbaren Prospekte oder Angebote. Spaeter erneut pruefen, wenn ADEG dort wieder Einzelangebote liefert.',
  },
  {
    retailerKey: 'adeg',
    retailerName: 'Adeg',
    channel: 'official-flyer',
    label: 'ADEG Flugblatt und Aktionen',
    sourceUrl: 'https://www.adeg.at/flugblatt-aktionen/adeg-flugblatt',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Deaktiviert: offizielle ADEG-Seite liefert derzeit keine verlaesslich strukturiert extrahierbaren Einzelangebote; PDF-/Bildprospekt-Parsing waere fuer diese fruehe Version unverhaeltnismaessig.',
  },
  {
    retailerKey: 'hofer',
    retailerName: 'Hofer',
    channel: 'aggregator',
    label: 'Aktionsfinder HOFER Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/hofer/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung.',
  },
  {
    retailerKey: 'hofer',
    retailerName: 'Hofer',
    channel: 'official-flyer',
    label: 'HOFER aktuelle Flugblaetter und Broschueren',
    sourceUrl: 'https://www.hofer.at/de/angebote/aktuelle-flugblaetter-und-broschuren.html',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle HOFER-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'hofer',
    retailerName: 'Hofer',
    channel: 'aggregator',
    label: 'Marktguru HOFER Angebote',
    sourceUrl: 'https://www.marktguru.at/r/hofer',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; Aktionsfinder/offizielle Quellen decken HOFER aktuell verlaesslicher ab. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'lidl',
    retailerName: 'Lidl',
    channel: 'aggregator',
    label: 'Aktionsfinder Lidl Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/lidl/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung.',
  },
  {
    retailerKey: 'lidl',
    retailerName: 'Lidl',
    channel: 'official-flyer',
    label: 'Lidl Flugblatt',
    sourceUrl: 'https://www.lidl.at/c/flugblatt/s10012330',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle Lidl-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'lidl',
    retailerName: 'Lidl',
    channel: 'aggregator',
    label: 'Marktguru Lidl Angebote',
    sourceUrl: 'https://www.marktguru.at/r/lidl',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; Aktionsfinder/offizielle Quellen decken Lidl aktuell verlaesslicher ab. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'aggregator',
    label: 'Aktionsfinder SPAR Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/spar/',
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Sekundaere Quelle fuer Lueckenanalyse und Ergaenzung. Offizielle SPAR-Quellen haben Vorrang; low-confidence PPCV bleibt ausgeschlossen.',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    channel: 'aggregator',
    label: 'Aktionsfinder INTERSPAR Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/interspar/',
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    appliesToRetailerFormats: ['interspar'],
    retailerFormatLabel: 'nur INTERSPAR',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Sekundaere INTERSPAR-Quelle fuer Lueckenanalyse und Ergaenzung. Nicht mit SPAR zusammenfassen.',
  },
  {
    retailerKey: 'eurospar',
    retailerName: 'EUROSPAR',
    channel: 'aggregator',
    label: 'Aktionsfinder EUROSPAR Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/eurospar/',
    sourceRetailerName: 'EUROSPAR',
    sourceRetailerFormat: 'eurospar',
    appliesToRetailerFormats: ['eurospar'],
    retailerFormatLabel: 'nur EUROSPAR',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Sekundaere EUROSPAR-Quelle fuer Lueckenanalyse und Ergaenzung. Nicht mit SPAR zusammenfassen.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'official-flyer',
    label: 'SPAR Steiermark offizielles PDF-Flugblatt KW 21',
    sourceUrl: 'https://flugblatt.spar.at/steiermark/spar/260521-1-flugblatt-kw-21/getPdf.ashx',
    sourceType: 'pdf',
    priority: 20,
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    crawlPolicy: {
      timeoutMs: 60000,
      maxPdfBytes: 41943040,
      maxPdfPages: 6,
      validityText: 'Do., 21.05.26 - Di., 02.06.26',
      validFrom: '2026-05-21T12:00:00.000Z',
      validTo: '2026-06-02T12:00:00.000Z',
      extractionMethod: 'text-layer',
      ocr: false,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Direkt erreichbares offizielles SPAR PDF-Flugblatt fuer Steiermark. Nur Textlayer, kein OCR, keine Request-Pfad-Verarbeitung. Statischer KW-21-Snapshot; nach Ablauf gezielt aktualisieren.',
  },
  {
    retailerKey: 'eurospar',
    retailerName: 'EUROSPAR',
    channel: 'official-flyer',
    label: 'EUROSPAR Steiermark offizielles PDF-Flugblatt KW 21',
    sourceUrl: 'https://flugblatt.spar.at/steiermark/eurospar/260521-1-flugblatt-kw-21/getPdf.ashx',
    sourceType: 'pdf',
    priority: 20,
    sourceRetailerName: 'EUROSPAR',
    sourceRetailerFormat: 'eurospar',
    appliesToRetailerFormats: ['eurospar'],
    retailerFormatLabel: 'nur EUROSPAR',
    crawlPolicy: {
      timeoutMs: 60000,
      maxPdfBytes: 41943040,
      maxPdfPages: 6,
      validityText: 'Do., 21.05.26 - Di., 02.06.26',
      validFrom: '2026-05-21T12:00:00.000Z',
      validTo: '2026-06-02T12:00:00.000Z',
      extractionMethod: 'text-layer',
      ocr: false,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Direkt erreichbares offizielles EUROSPAR PDF-Flugblatt fuer Steiermark. Nur Textlayer, kein OCR, keine Request-Pfad-Verarbeitung. Statischer KW-21-Snapshot; nach Ablauf gezielt aktualisieren.',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    channel: 'official-flyer',
    label: 'INTERSPAR Steiermark offizielles PDF-Flugblatt KW 21',
    sourceUrl: 'https://flugblatt.interspar.at/steiermark/steiermark_kw21/getPdf.ashx',
    sourceType: 'pdf',
    priority: 20,
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    appliesToRetailerFormats: ['interspar'],
    retailerFormatLabel: 'nur INTERSPAR',
    crawlPolicy: {
      timeoutMs: 60000,
      maxPdfBytes: 41943040,
      maxPdfPages: 6,
      validityText: 'Do., 21.05.26 - Mi., 02.06.26',
      validFrom: '2026-05-21T12:00:00.000Z',
      validTo: '2026-06-02T12:00:00.000Z',
      extractionMethod: 'text-layer',
      ocr: false,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Direkt erreichbares offizielles INTERSPAR PDF-Flugblatt fuer Steiermark. Nur Textlayer, kein OCR, keine Request-Pfad-Verarbeitung. Statischer KW-21-Snapshot; nach Ablauf gezielt aktualisieren.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'official-site',
    label: 'SPAR Aktionen Steiermark',
    sourceUrl: 'https://www.spar.at/aktionen/steiermark',
    sourceType: 'offers-page',
    priority: 5,
    parserHint: 'official-category-actions',
    parserVersion: 'official-category-promotions-v1',
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    regionScope: 'Steiermark',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle SPAR-Aktionsseite fuer Steiermark. Parser erfasst nur belegte Kategorie-/Prozentaktionen ohne Einzelproduktpreise.',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    channel: 'official-site',
    label: 'INTERSPAR Aktionen',
    sourceUrl: 'https://www.interspar.at/aktionen',
    sourceType: 'offers-page',
    priority: 5,
    parserHint: 'official-category-actions',
    parserVersion: 'official-category-promotions-v1',
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    appliesToRetailerFormats: ['interspar'],
    retailerFormatLabel: 'nur INTERSPAR',
    regionScope: 'Austria',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle INTERSPAR-Aktionsseite. Parser erfasst nur belegte Kategorie-/Prozentaktionen ohne Einzelproduktpreise.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'aggregator',
    label: 'Marktguru SPAR Angebote',
    sourceUrl: 'https://www.marktguru.at/r/spar',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; Aktionsfinder-SPAR-Formate decken SPAR aktuell verlaesslicher ab. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'aggregator',
    label: 'Aktionsfinder BILLA Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/billa/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'official-flyer',
    label: 'BILLA Flugblatt',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/flugblatt',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle BILLA-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'official-site',
    label: 'BILLA Aktionen',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/aktionen',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BILLA-Aktionsseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'aggregator',
    label: 'Marktguru BILLA Angebote',
    sourceUrl: 'https://www.marktguru.at/r/billa',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; offizielle BILLA-Quelle und Aktionsfinder liefern aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'aggregator',
    label: 'Aktionsfinder BILLA PLUS Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/billa-plus/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'official-flyer',
    label: 'BILLA PLUS Flugblatt',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/flugblatt',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle BILLA/BILLA PLUS-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'official-site',
    label: 'BILLA PLUS Aktionen',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/aktionen',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BILLA/BILLA PLUS-Aktionsseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'aggregator',
    label: 'Marktguru BILLA PLUS Angebote',
    sourceUrl: 'https://www.marktguru.at/r/billa-plus',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; offizielle BILLA/BILLA PLUS-Quelle und Aktionsfinder liefern aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'official-site',
    label: 'PENNY Angebote',
    sourceUrl: 'https://www.penny.at/angebote',
    priority: 1,
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Priorisierte offizielle PENNY-Angebotsseite mit serverseitig gerenderten Produktaktionen als stabile Primaerquelle.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'official-flyer',
    label: 'PENNY Flugblaetter',
    sourceUrl: 'https://www.penny.at/angebote/flugblaetter',
    priority: 8,
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle PENNY-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'aggregator',
    label: 'Aktionsfinder PENNY Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/penny/',
    priority: 20,
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung, nach offizieller PENNY-Quelle.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'aggregator',
    label: 'Marktguru PENNY Angebote',
    sourceUrl: 'https://www.marktguru.at/r/penny',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; PENNY offizielle Quelle und Aktionsfinder liefern aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'aggregator',
    label: 'Aktionsfinder dm drogerie markt Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/dm-drogerie-markt/',
    sourceType: 'aggregator',
    priority: 15,
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Breite oeffentliche Aktionsfinder-Quelle fuer aktuelle dm-Angebote und Prospekte.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'official-site',
    label: 'dm Ausverkauf',
    sourceUrl: 'https://www.dm.at/ausverkauf',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle dm-Ausverkaufseite als konservative Primaerquelle. Normale Sortimentsseiten werden nicht als Angebot gespeichert.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'aggregator',
    label: 'Marktguru dm Angebote',
    sourceUrl: 'https://www.marktguru.at/r/dm',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; Aktionsfinder/wogibtswas liefern aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'aggregator',
    label: 'wogibtswas dm Angebote',
    sourceUrl: 'https://www.wogibtswas.at/h/73424-dm',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Zusaetzliche oeffentliche Produkt- und Flugblattquelle fuer aktuelle dm-Angebote.',
  },
  {
    retailerKey: 'pagro',
    retailerName: 'PAGRO',
    channel: 'official-site',
    label: 'PAGRO Angebote',
    sourceUrl: 'https://www.pagro.at/angebote',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-cloudflare-source',
    priority: 10,
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle PAGRO-Angebotsseite zeigt Produktangebote mit Preisen/Pagination, lokale Node-Fetches erhalten aber Cloudflare-Challenge. Erst aktivieren, wenn eine erlaubte stabile HTML/API-Quelle verfuegbar ist.',
  },
  {
    retailerKey: 'pagro',
    retailerName: 'PAGRO',
    channel: 'aggregator',
    label: 'Aktionsfinder PAGRO & LIBRO Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/pagro-libro/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Breite oeffentliche Aggregator-Quelle fuer aktuelle PAGRO & LIBRO Aktionen.',
  },
  {
    retailerKey: 'pagro',
    retailerName: 'PAGRO',
    channel: 'aggregator',
    label: 'Marktguru PAGRO Angebote',
    sourceUrl: 'https://www.marktguru.at/r/pagro',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; Aktionsfinder liefert aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'bipa',
    retailerName: 'BIPA',
    channel: 'official-site',
    label: 'BIPA Aktionen',
    sourceUrl: 'https://www.bipa.at/cp/aktionen',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BIPA-Aktionsseite mit Produktkacheln und Aktionslisten als Primaerquelle.',
  },
  {
    retailerKey: 'bipa',
    retailerName: 'BIPA',
    channel: 'aggregator',
    label: 'Aktionsfinder BIPA Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/bipa/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle BIPA-Angebotsabdeckung.',
  },
  {
    retailerKey: 'bipa',
    retailerName: 'BIPA',
    channel: 'aggregator',
    label: 'Marktguru BIPA Angebote',
    sourceUrl: 'https://www.marktguru.at/r/bipa',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; BIPA offizielle Quelle und Aktionsfinder liefern aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
];

module.exports = {
  RETAILER_DEFINITIONS,
};
