const SPAR_FAMILY_PDF_FORMATS = [
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    retailerFormatLabel: 'nur SPAR',
  },
  {
    retailerKey: 'eurospar',
    retailerName: 'EUROSPAR',
    sourceRetailerName: 'EUROSPAR',
    sourceRetailerFormat: 'eurospar',
    retailerFormatLabel: 'nur EUROSPAR',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    retailerFormatLabel: 'nur INTERSPAR',
  },
];

function buildSparFamilySharedPdfSources({
  label,
  sourceUrl,
  priority = 22,
  validFrom,
  validTo,
  validityText,
  maxPdfPages = 24,
  requireCouponCondition = false,
  notes,
}) {
  return SPAR_FAMILY_PDF_FORMATS.map((format) => ({
    retailerKey: format.retailerKey,
    retailerName: format.retailerName,
    channel: 'official-flyer',
    label: `${format.retailerName} ${label}`,
    sourceUrl,
    sourceType: 'pdf',
    priority,
    sourceRetailerName: format.sourceRetailerName,
    sourceRetailerFormat: format.sourceRetailerFormat,
    appliesToRetailerFormats: [format.sourceRetailerFormat],
    retailerFormatLabel: format.retailerFormatLabel,
    crawlPolicy: {
      timeoutMs: 60000,
      sourceTimeoutMs: 180000,
      maxPdfBytes: 62914560,
      maxPdfPages,
      scopedOnly: true,
      coverageGuard: {
        minBaseline: 1,
        minReplacementRatio: 0.1,
        minAbsoluteDrop: 10,
      },
      validityText,
      validFrom,
      validTo,
      currentSnapshot: false,
      extractionMethod: 'text-layer',
      ocr: false,
      requireCouponCondition,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes,
  }));
}

const RETAILER_DEFINITIONS = [
  {
    retailerKey: 'adeg',
    retailerName: 'Adeg',
    channel: 'aggregator',
    label: 'Aktionsfinder ADEG Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/adeg/',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder meldet aktuell fuer ADEG keine oeffentlich extrahierbaren Prospekte oder Angebote. Spaeter erneut pruefen, wenn ADEG dort wieder Einzelangebote liefert.',
  },
  {
    retailerKey: 'adeg',
    retailerName: 'Adeg',
    channel: 'official-flyer',
    label: 'ADEG Flugblatt und Aktionen',
    sourceUrl: 'https://www.adeg.at/flugblatt-aktionen/adeg-flugblatt',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Deaktiviert: offizielle ADEG-Seite liefert derzeit keine verlaesslich strukturiert extrahierbaren Einzelangebote; PDF-/Bildprospekt-Parsing waere fuer diese fruehe Version unverhaeltnismaessig.',
  },
  {
    retailerKey: 'hofer',
    retailerName: 'Hofer',
    channel: 'aggregator',
    label: 'Aktionsfinder HOFER Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/hofer/',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/hofer liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. Nicht reaktivieren ohne neue read-only Evidence.',
  },
  {
    retailerKey: 'hofer',
    retailerName: 'Hofer',
    channel: 'official-flyer',
    label: 'HOFER aktuelle Flugblaetter und Broschueren',
    sourceUrl: 'https://www.hofer.at/de/angebote/aktuelle-flugblaetter-und-broschuren.html',
    crawlPolicy: {
      discoverySeedUrls: [
        'https://www.hofer.at/de/angebote/angebote-im-ueberblick.html?productState=In+der+Filiale+erh%C3%A4ltlich',
        'https://www.hofer.at/de/angebote/aktionen.html',
        'https://www.hofer.at/de/angebote/hofer-preiswochen.html',
        'https://www.hofer.at/de/angebote/hofer-preis-dauerhaft-guenstiger.html',
        'https://www.hofer.at/de/angebote/technik-und-haushalt.html',
        'https://www.hofer.at/de/angebote/handys-und-router.html',
      ],
      discoverDatedOfferPages: true,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle HOFER-Flugblattseite als zusaetzliche Primaerquelle. Angebots-, Preiswochen-, Dauerpreis-, Technik-/Haushalt- und Handy-/Router-Seiten sind Discovery-Seeds; Datumsseiten muessen dynamisch entdeckt werden und werden nicht statisch hardcodiert.',
  },
  {
    retailerKey: 'hofer',
    retailerName: 'Hofer',
    channel: 'aggregator',
    label: 'Marktguru HOFER Angebote',
    sourceUrl: 'https://www.marktguru.at/r/hofer',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; Aktionsfinder/offizielle Quellen decken HOFER aktuell verlaesslicher ab. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'lidl',
    retailerName: 'Lidl',
    channel: 'aggregator',
    label: 'Aktionsfinder Lidl Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/lidl/',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/lidl liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. Lidl braucht separate offizielle Source-Verbesserung statt kaputtem Aggregator-Fallback.',
  },
  {
    retailerKey: 'lidl',
    retailerName: 'Lidl',
    channel: 'official-flyer',
    label: 'Lidl Flugblatt',
    sourceUrl: 'https://www.lidl.at/c/flugblatt/s10012330',
    crawlPolicy: {
      webOfferSeedUrls: [
        'https://www.lidl.at/',
      ],
      campaignSeedUrls: [
        'https://www.lidl.at/c/mega-deals/s10091719',
        'https://www.lidl.at/c/aktion/a10095240',
        'https://www.lidl.at/c/frische-angebote/a10095239',
        'https://www.lidl.at/c/jeden-tag-deine-guenstigen-preise/a10095237',
        'https://www.lidl.at/c/blumen-pflanzen/a10095234',
        'https://www.lidl.at/c/super-frische/s10013062',
        'https://www.lidl.at/c/mit-jedem-bissen-kurzurlaub-machen/a10095235',
        'https://www.lidl.at/c/beim-grillen-richtig-kohle-sparen/a10095236',
      ],
      discoverCampaignPages: true,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle Lidl-Flugblattseite als zusaetzliche Primaerquelle. Kampagnen-URLs sind volatile Seeds und werden mit dynamischer Discovery aus offiziellen Links kombiniert.',
  },
  {
    retailerKey: 'lidl',
    retailerName: 'Lidl',
    channel: 'aggregator',
    label: 'Marktguru Lidl Angebote',
    sourceUrl: 'https://www.marktguru.at/r/lidl',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; Aktionsfinder/offizielle Quellen decken Lidl aktuell verlaesslicher ab. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'aggregator',
    label: 'Aktionsfinder SPAR Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/spar/',
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/spar liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. SPAR-Coverage separat ueber offizielle Quellen/PDF/Productworld entscheiden.',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    channel: 'aggregator',
    label: 'Aktionsfinder INTERSPAR Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/interspar/',
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    appliesToRetailerFormats: ['interspar'],
    retailerFormatLabel: 'nur INTERSPAR',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/interspar liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. Nicht mit SPAR zusammenfassen; offizielle INTERSPAR-Quellen separat bewerten.',
  },
  {
    retailerKey: 'eurospar',
    retailerName: 'EUROSPAR',
    channel: 'aggregator',
    label: 'Aktionsfinder EUROSPAR Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/eurospar/',
    sourceRetailerName: 'EUROSPAR',
    sourceRetailerFormat: 'eurospar',
    appliesToRetailerFormats: ['eurospar'],
    retailerFormatLabel: 'nur EUROSPAR',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/eurospar liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. Nicht mit SPAR zusammenfassen; offizielle EUROSPAR-Quellen separat bewerten.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'official-flyer',
    label: 'SPAR Steiermark offizielles PDF-Flugblatt KW 23',
    sourceUrl: 'https://flugblatt.spar.at/steiermark/spar/260603-1-flugblatt-kw-23/getPdf.ashx',
    sourceType: 'pdf',
    priority: 20,
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    crawlPolicy: {
      timeoutMs: 60000,
      maxPdfBytes: 62914560,
      maxPdfPages: 28,
      coverageGuard: {
        minBaseline: 50,
        minReplacementRatio: 0.35,
        minAbsoluteDrop: 25,
      },
      scopedOnly: true,
      currentSnapshot: false,
      validityText: 'Mi., 03.06.26 - Mi., 17.06.26',
      validFrom: '2026-06-02T22:00:00.000Z',
      validTo: '2026-06-17T21:59:59.999Z',
      extractionMethod: 'text-layer',
      ocr: false,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Direkt per GET validiertes offizielles SPAR PDF-Flugblatt fuer Steiermark. Nur Textlayer, kein OCR, keine Request-Pfad-Verarbeitung. Statischer KW-23-Snapshot; scoped-only, damit Full Crawls ihn nicht als aktuelle Discovery-Wahrheit behandeln.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'official-flyer',
    label: 'SPAR Steiermark offizielles PDF-Obst und Gemuese KW 23',
    sourceUrl: 'https://flugblatt.spar.at/steiermark/spar/260601-1-obst-gemuse-kw-23/getPdf.ashx',
    sourceType: 'pdf',
    priority: 21,
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    crawlPolicy: {
      timeoutMs: 60000,
      maxPdfBytes: 10485760,
      maxPdfPages: 2,
      scopedOnly: true,
      currentSnapshot: false,
      coverageGuard: {
        minBaseline: 6,
        minReplacementRatio: 0.35,
        minAbsoluteDrop: 4,
      },
      validityText: 'Mo., 01.06.26 - Sa., 06.06.26',
      validFrom: '2026-05-31T22:00:00.000Z',
      validTo: '2026-06-06T21:59:59.999Z',
      extractionMethod: 'text-layer',
      ocr: false,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Direkt per GET validiertes offizielles SPAR Obst-und-Gemuese PDF KW 23 fuer Steiermark. Scoped-only, nur Textlayer, kein OCR.',
  },
  {
    retailerKey: 'eurospar',
    retailerName: 'EUROSPAR',
    channel: 'official-flyer',
    label: 'EUROSPAR Steiermark offizielles PDF-Flugblatt KW 23',
    sourceUrl: 'https://flugblatt.spar.at/steiermark/eurospar/260603-1-flugblatt-kw-23/getPdf.ashx',
    sourceType: 'pdf',
    priority: 20,
    sourceRetailerName: 'EUROSPAR',
    sourceRetailerFormat: 'eurospar',
    appliesToRetailerFormats: ['eurospar'],
    retailerFormatLabel: 'nur EUROSPAR',
    crawlPolicy: {
      timeoutMs: 60000,
      maxPdfBytes: 62914560,
      maxPdfPages: 24,
      coverageGuard: {
        minBaseline: 50,
        minReplacementRatio: 0.35,
        minAbsoluteDrop: 25,
      },
      scopedOnly: true,
      currentSnapshot: false,
      validityText: 'Mi., 03.06.26 - Mi., 17.06.26',
      validFrom: '2026-06-02T22:00:00.000Z',
      validTo: '2026-06-17T21:59:59.999Z',
      extractionMethod: 'text-layer',
      ocr: false,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Direkt per GET validiertes offizielles EUROSPAR PDF-Flugblatt fuer Steiermark. Nur Textlayer, kein OCR, keine Request-Pfad-Verarbeitung. Statischer KW-23-Snapshot; scoped-only, damit Full Crawls ihn nicht als aktuelle Discovery-Wahrheit behandeln.',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    channel: 'official-flyer',
    label: 'INTERSPAR Steiermark offizielles PDF-Flugblatt KW 23',
    sourceUrl: 'https://flugblatt.interspar.at/steiermark/steiermark_kw23/getPdf.ashx',
    sourceType: 'pdf',
    priority: 20,
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    appliesToRetailerFormats: ['interspar'],
    retailerFormatLabel: 'nur INTERSPAR',
    crawlPolicy: {
      timeoutMs: 60000,
      maxPdfBytes: 62914560,
      maxPdfPages: 24,
      coverageGuard: {
        minBaseline: 50,
        minReplacementRatio: 0.35,
        minAbsoluteDrop: 25,
      },
      scopedOnly: true,
      currentSnapshot: false,
      validityText: 'Mi., 03.06.26 - Mi., 17.06.26',
      validFrom: '2026-06-02T22:00:00.000Z',
      validTo: '2026-06-17T21:59:59.999Z',
      extractionMethod: 'text-layer',
      ocr: false,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Direkt per GET validiertes offizielles INTERSPAR PDF-Flugblatt fuer Steiermark. Nur Textlayer, kein OCR, keine Request-Pfad-Verarbeitung. Statischer KW-23-Snapshot; scoped-only, damit Full Crawls ihn nicht als aktuelle Discovery-Wahrheit behandeln.',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    channel: 'official-flyer',
    label: 'INTERSPAR offizielles PDF weinwelt-Bestseller 06-2026',
    sourceUrl: 'https://flugblatt.interspar.at/weinwelt/260511-4-weinwelt-bestseller-06-2026/getPdf.ashx',
    sourceType: 'pdf',
    priority: 21,
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    appliesToRetailerFormats: ['interspar'],
    retailerFormatLabel: 'nur INTERSPAR',
    crawlPolicy: {
      timeoutMs: 60000,
      maxPdfBytes: 41943040,
      maxPdfPages: 28,
      scopedOnly: true,
      currentSnapshot: false,
      coverageGuard: {
        minBaseline: 6,
        minReplacementRatio: 0.35,
        minAbsoluteDrop: 4,
      },
      validityText: 'Mi., 13.05.26 - Mi., 10.06.26',
      validFrom: '2026-05-12T22:00:00.000Z',
      validTo: '2026-06-10T21:59:59.999Z',
      extractionMethod: 'text-layer',
      ocr: false,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Direkt per GET validierter offizieller INTERSPAR weinwelt-Bestseller PDF-Endpunkt. Scoped-only, nur Textlayer, kein OCR; nicht den 404-Slug mit Unterstrich/Grossschreibung verwenden.',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    channel: 'official-flyer',
    label: 'INTERSPAR offizielles PDF Mein Zuhause Magazin Sommer 2026',
    sourceUrl: 'https://flugblatt.interspar.at/sonderfolder/mein-zuhause-sommer26/getPdf.ashx',
    sourceType: 'pdf',
    priority: 22,
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    appliesToRetailerFormats: ['interspar'],
    retailerFormatLabel: 'nur INTERSPAR',
    crawlPolicy: {
      timeoutMs: 60000,
      maxPdfBytes: 41943040,
      maxPdfPages: 48,
      scopedOnly: true,
      currentSnapshot: false,
      coverageGuard: {
        minBaseline: 8,
        minReplacementRatio: 0.35,
        minAbsoluteDrop: 5,
      },
      validityText: 'Di., 07.04.26 - Fr., 31.07.26',
      validFrom: '2026-04-06T22:00:00.000Z',
      validTo: '2026-07-31T21:59:59.999Z',
      extractionMethod: 'text-layer',
      ocr: false,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Direkt per GET validierter offizieller INTERSPAR Mein-Zuhause-Sommer-2026 PDF-Endpunkt. Scoped-only, nur Textlayer, kein OCR.',
  },
  ...buildSparFamilySharedPdfSources({
    label: 'Steiermark offizieller PDF-Monatssparer KW 20',
    sourceUrl: 'https://flugblatt.spar.at/steiermark/spar/260513-3-monatssparer-kw-20/getPdf.ashx',
    priority: 21,
    validityText: 'Mi., 13.05.26 - Mi., 10.06.26',
    validFrom: '2026-05-12T22:00:00.000Z',
    validTo: '2026-06-10T21:59:59.999Z',
    maxPdfPages: 12,
    notes: 'Direkt per GET validierter offizieller SPAR-Family Monatssparer. Scoped-only Fallback fuer aktuelle Coverage; kein OCR, nur Textlayer.',
  }),
  ...buildSparFamilySharedPdfSources({
    label: 'Steiermark offizieller PDF-Grillfolder KW 20',
    sourceUrl: 'https://flugblatt.spar.at/steiermark/spar/260513-2-grillen-kw-20/getPdf.ashx',
    priority: 22,
    validityText: 'Mi., 13.05.26 - Mi., 10.06.26',
    validFrom: '2026-05-12T22:00:00.000Z',
    validTo: '2026-06-10T21:59:59.999Z',
    maxPdfPages: 8,
    notes: 'Direkt per GET validierter offizieller SPAR-Family Grillfolder. Scoped-only Fallback fuer aktuelle Coverage; kein OCR, nur Textlayer.',
  }),
  ...buildSparFamilySharedPdfSources({
    label: 'Steiermark offizielles PDF-Gutscheinheft KW 22',
    sourceUrl: 'https://flugblatt.spar.at/steiermark/spar/260528-3-spar-gutscheinheft-kw-22/getPdf.ashx',
    priority: 23,
    validityText: 'Do., 28.05.26 - Mi., 17.06.26',
    validFrom: '2026-05-27T22:00:00.000Z',
    validTo: '2026-06-17T21:59:59.999Z',
    maxPdfPages: 24,
    requireCouponCondition: true,
    notes: 'Direkt per GET validiertes offizielles SPAR-Family Gutscheinheft. Accepted Offers werden explizit als Gutschein-Angebote markiert; kein OCR, nur Textlayer.',
  }),
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'official-site',
    label: 'SPAR Produktwelt offizielle BFF-Angebote',
    sourceUrl: 'https://api-scp.spar-ics.com/ecom/pw/v1/search/v1/search?marketId=NATIONAL&filters=inAngebot,isPreisGesenkt',
    sourceType: 'spar-family-official-productworld',
    priority: 1,
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'production-productworld-crawl-429-rate-limit-1015',
    parserHint: 'official-productworld-bff',
    parserVersion: 'spar-productworld-bff-v1',
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    regionScope: 'Oesterreich / Produktwelt NATIONAL',
    crawlPolicy: {
      scopedOnly: true,
      sourceTimeoutMs: 180000,
      marketId: 'NATIONAL',
      pageSize: 48,
      maxPagesPerFilter: 80,
      delayMs: 250,
    },
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Vorbereitet, aber deaktiviert nach Production-Crawl 2026-06-05: DigitalOcean Node HTTP/2 liefert kleine Diagnose-JSONs, ein echter scoped Crawl traf jedoch Cloudflare Rate Limit 429/error code 1015. Keine Aktivierung bis konservativer BFF-Batch-/Backoff-Pfad produktiv validiert ist.',
  },
  {
    retailerKey: 'eurospar',
    retailerName: 'EUROSPAR',
    channel: 'official-site',
    label: 'EUROSPAR Produktwelt offizielle BFF-Angebote',
    sourceUrl: 'https://api-scp.spar-ics.com/ecom/pw/v1/search/v1/search?marketId=EUROSPAR&filters=inAngebot,isPreisGesenkt',
    sourceType: 'spar-family-official-productworld',
    priority: 1,
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'production-productworld-eurospar-inangebot-403',
    parserHint: 'official-productworld-bff',
    parserVersion: 'spar-productworld-bff-v1',
    sourceRetailerName: 'EUROSPAR',
    sourceRetailerFormat: 'eurospar',
    appliesToRetailerFormats: ['eurospar'],
    retailerFormatLabel: 'nur EUROSPAR',
    regionScope: 'Oesterreich / Produktwelt EUROSPAR',
    crawlPolicy: {
      scopedOnly: true,
      sourceTimeoutMs: 180000,
      marketId: 'EUROSPAR',
      pageSize: 48,
      maxPagesPerFilter: 90,
      delayMs: 250,
    },
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Weiter deaktiviert nach Production-Transport-Matrix 2026-06-05: marketId=EUROSPAR liefert per Node HTTP/2 JSON fuer isPreisGesenkt, aber inAngebot bleibt Cloudflare-403. Crawler erwartet beide Filter; daher keine Teilaktivierung/Fake-Coverage.',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    channel: 'official-site',
    label: 'INTERSPAR Produktwelt offizielle BFF-Angebote',
    sourceUrl: 'https://api-scp.spar-ics.com/ecom/pw/v1/search/v1/search?marketId=INTERSPAR&filters=inAngebot,isPreisGesenkt',
    sourceType: 'spar-family-official-productworld',
    priority: 1,
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'production-productworld-crawl-429-rate-limit-1015',
    parserHint: 'official-productworld-bff',
    parserVersion: 'spar-productworld-bff-v1',
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    appliesToRetailerFormats: ['interspar'],
    retailerFormatLabel: 'nur INTERSPAR',
    regionScope: 'Oesterreich / Produktwelt INTERSPAR',
    crawlPolicy: {
      scopedOnly: true,
      sourceTimeoutMs: 240000,
      marketId: 'INTERSPAR',
      pageSize: 48,
      maxPagesPerFilter: 100,
      delayMs: 250,
    },
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Vorbereitet, aber deaktiviert nach Production-Crawl 2026-06-05: DigitalOcean Node HTTP/2 liefert kleine Diagnose-JSONs, ein echter scoped Crawl traf jedoch Cloudflare Rate Limit 429/error code 1015. Keine Aktivierung bis konservativer BFF-Batch-/Backoff-Pfad produktiv validiert ist.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'official-flyer',
    label: 'SPAR Steiermark aktuelle Flugblatt-Discovery',
    sourceUrl: 'https://www.spar.at/aktionen/steiermark',
    sourceType: 'flyer',
    priority: 5,
    parserHint: 'spar-family-flyer-discovery',
    parserVersion: 'spar-family-flyer-discovery-v1',
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    regionScope: 'Steiermark',
    crawlPolicy: {
      scopedOnly: true,
      currentDiscovery: true,
      currentSnapshot: true,
      entryPoints: ['https://www.spar.at/aktionen/steiermark'],
      fallbackViewerUrls: ['https://flugblatt.spar.at/steiermark/spar/260618-1-flugblatt-kw-25/getPdf.ashx'],
      maxEntryPoints: 1,
      maxLinks: 20,
      maxPdfMetadataLookups: 1,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle SPAR Steiermark Listingseite als Current-Flyer-Discovery-Quelle. Separat vom deaktivierten Kategorieaktions-Parser; kein Productworld-/Aggregator-Fallback, keine Token-/Session-Umgehung und scoped-only bis ein freigegebener Dry-Run/Scoped-Crawl die Discovery validiert.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'official-site',
    label: 'SPAR Produktwelt Bier Angebote',
    sourceUrl: 'https://www.spar.at/produktwelt/bier?inAngebot=true&page=1',
    sourceType: 'offers-page',
    priority: 8,
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'resource-required-official-productworld-blocked',
    parserHint: 'official-product-world',
    parserVersion: 'planned',
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    regionScope: 'Steiermark',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Geplante offizielle Produktwelt-Quelle fuer Bier-Angebote. Lokal derzeit TLS/403/JS-Risiko; erst aktivieren, wenn eine legal direkt crawlbare HTML-/JSON-/Asset-Ressource mit Preis-/Validity-Evidence vorliegt.',
  },
  {
    retailerKey: 'eurospar',
    retailerName: 'EUROSPAR',
    channel: 'official-flyer',
    label: 'EUROSPAR Steiermark aktuelle Flugblatt-Discovery',
    sourceUrl: 'https://www.spar.at/aktionen/steiermark/eurospar',
    sourceType: 'flyer',
    priority: 5,
    parserHint: 'spar-family-flyer-discovery',
    parserVersion: 'spar-family-flyer-discovery-v1',
    sourceRetailerName: 'EUROSPAR',
    sourceRetailerFormat: 'eurospar',
    appliesToRetailerFormats: ['eurospar'],
    retailerFormatLabel: 'nur EUROSPAR',
    regionScope: 'Steiermark',
    crawlPolicy: {
      scopedOnly: true,
      currentDiscovery: true,
      currentSnapshot: true,
      entryPoints: ['https://www.spar.at/aktionen/steiermark/eurospar'],
      maxEntryPoints: 1,
      maxLinks: 20,
      maxPdfMetadataLookups: 0,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle EUROSPAR Steiermark Listingseite als Current-Flyer-Discovery-Quelle. Nicht mit SPAR gleichsetzen; kein Productworld-/Aggregator-Fallback, keine Token-/Session-Umgehung und scoped-only bis ein freigegebener Dry-Run/Scoped-Crawl die Discovery validiert.',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    channel: 'official-site',
    label: 'INTERSPAR Aktionen Steiermark auf SPAR',
    sourceUrl: 'https://www.spar.at/aktionen/steiermark/interspar',
    sourceType: 'offers-page',
    priority: 5,
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'resource-required-official-action-page-blocked',
    parserHint: 'official-category-actions',
    parserVersion: 'official-category-promotions-v1',
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    appliesToRetailerFormats: ['interspar'],
    retailerFormatLabel: 'nur INTERSPAR',
    regionScope: 'Steiermark',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Geplante SPAR-Domain-Quelle fuer INTERSPAR Steiermark. Separat von interspar.at speichern und erst nach Redirect-/Content-Audit aktivieren.',
  },
  {
    retailerKey: 'interspar',
    retailerName: 'INTERSPAR',
    channel: 'official-flyer',
    label: 'INTERSPAR Steiermark aktuelle Flugblatt-Discovery',
    sourceUrl: 'https://www.interspar.at/aktionen/steiermark',
    sourceType: 'flyer',
    priority: 5,
    parserHint: 'spar-family-flyer-discovery',
    parserVersion: 'spar-family-flyer-discovery-v1',
    sourceRetailerName: 'INTERSPAR',
    sourceRetailerFormat: 'interspar',
    appliesToRetailerFormats: ['interspar'],
    retailerFormatLabel: 'nur INTERSPAR',
    regionScope: 'Steiermark',
    crawlPolicy: {
      scopedOnly: true,
      currentDiscovery: true,
      currentSnapshot: true,
      entryPoints: ['https://www.interspar.at/aktionen/steiermark'],
      fallbackViewerUrls: ['https://flugblatt.interspar.at/steiermark/steiermark_kw25/getPdf.ashx'],
      maxEntryPoints: 1,
      maxLinks: 20,
      maxPdfMetadataLookups: 1,
    },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle INTERSPAR Steiermark Listingseite als Current-Flyer-Discovery-Quelle. Separat von der deaktivierten SPAR-Domain-INTERSPAR-Planquelle; kein Productworld-/Aggregator-Fallback, keine Token-/Session-Umgehung und scoped-only bis ein freigegebener Dry-Run/Scoped-Crawl die Discovery validiert.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'SPAR',
    channel: 'aggregator',
    label: 'Marktguru SPAR Angebote',
    sourceUrl: 'https://www.marktguru.at/r/spar',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    sourceRetailerName: 'SPAR',
    sourceRetailerFormat: 'spar',
    appliesToRetailerFormats: ['spar'],
    retailerFormatLabel: 'nur SPAR',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; Aktionsfinder-SPAR-Formate decken SPAR aktuell verlaesslicher ab. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'aggregator',
    label: 'Aktionsfinder BILLA Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/billa/',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/billa liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. BILLA hat offizielle Quellen; Aggregator-Fallback derzeit nicht produktiv.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'official-flyer',
    label: 'BILLA Flugblatt',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/flugblatt',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle BILLA-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'official-flyer',
    label: 'BILLA Flugblatt Steiermark',
    sourceUrl: 'https://view.publitas.com/billa-at/billa_fb_kw24_2026_steiermark/',
    sourceType: 'flyer',
    priority: 2,
    regionScope: 'Steiermark',
    sourceRetailerName: 'BILLA',
    sourceRetailerFormat: 'billa',
    appliesToRetailerFormats: ['billa'],
    retailerFormatLabel: 'BILLA Steiermark',
    crawlPolicy: { regionLevel: 'Bundesland', maxPdfPages: 24, timeoutMs: 45000 },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizieller regionaler Publitas-Viewer fuer BILLA Steiermark KW24. Produktiv nur ueber offizielle Publitas-URL, keine lokale PDF-Hardcodierung.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'official-site',
    label: 'BILLA Aktionen',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/aktionen',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BILLA-Aktionsseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'aggregator',
    label: 'Marktguru BILLA Angebote',
    sourceUrl: 'https://www.marktguru.at/r/billa',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; offizielle BILLA-Quelle und Aktionsfinder liefern aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'aggregator',
    label: 'Aktionsfinder BILLA PLUS Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/billa-plus/',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/billa-plus liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. BILLA Plus hat offizielle Quellen; Aggregator-Fallback derzeit nicht produktiv.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'official-flyer',
    label: 'BILLA PLUS Flugblatt',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/flugblatt',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle BILLA/BILLA PLUS-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'official-flyer',
    label: 'BILLA PLUS Flugblatt Steiermark',
    sourceUrl: 'https://view.publitas.com/billa-plus/billa_plus_fb_kw24_2026_steiermark/',
    sourceType: 'flyer',
    priority: 2,
    regionScope: 'Steiermark',
    sourceRetailerName: 'BILLA PLUS',
    sourceRetailerFormat: 'billa-plus',
    appliesToRetailerFormats: ['billa-plus'],
    retailerFormatLabel: 'BILLA PLUS Steiermark',
    crawlPolicy: { regionLevel: 'Bundesland', maxPdfPages: 24, timeoutMs: 45000 },
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizieller regionaler Publitas-Viewer fuer BILLA PLUS Steiermark KW24. Produktiv nur ueber offizielle Publitas-URL, keine lokale PDF-Hardcodierung.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'official-site',
    label: 'BILLA PLUS Aktionen',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/aktionen',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BILLA/BILLA PLUS-Aktionsseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'aggregator',
    label: 'Marktguru BILLA PLUS Angebote',
    sourceUrl: 'https://www.marktguru.at/r/billa-plus',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; offizielle BILLA/BILLA PLUS-Quelle und Aktionsfinder liefern aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'official-site',
    label: 'PENNY Angebote',
    sourceUrl: 'https://www.penny.at/angebote',
    priority: 1,
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Priorisierte offizielle PENNY-Angebotsseite mit serverseitig gerenderten Produktaktionen als stabile Primaerquelle.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'official-flyer',
    label: 'PENNY Flugblaetter',
    sourceUrl: 'https://www.penny.at/angebote/flugblaetter',
    priority: 8,
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle PENNY-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'official-site',
    label: 'PENNY Dauer guenstig',
    sourceUrl: 'https://www.penny.at/sortiment/dauer-guenstig',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'planned-dauerpreis-not-temporary-offer-source',
    priority: 25,
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle Dauerpreis-Quelle aus der Resource-Matrix. Nicht als befristetes Angebot behandeln; erst mit separater Dauerpreis-/Preisversprechen-Logik aktivieren.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'aggregator',
    label: 'Aktionsfinder PENNY Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/penny/',
    priority: 20,
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/penny liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. PENNY hat offizielle Quellen; Trust/Conditions bleiben separater Hebel.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'aggregator',
    label: 'Marktguru PENNY Angebote',
    sourceUrl: 'https://www.marktguru.at/r/penny',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; PENNY offizielle Quelle und Aktionsfinder liefern aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'aggregator',
    label: 'Aktionsfinder dm drogerie markt Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/dm-drogerie-markt/',
    sourceType: 'aggregator',
    priority: 15,
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/dm-drogerie-markt liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. dm hat offizielle/wogibtswas-Alternativen; Bild-/Qualitaetshebel separat bewerten.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'official-site',
    label: 'dm Ausverkauf',
    sourceUrl: 'https://www.dm.at/ausverkauf',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle dm-Ausverkaufseite als konservative Primaerquelle. Normale Sortimentsseiten werden nicht als Angebot gespeichert.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'official-site',
    label: 'dm Immerguenstig',
    sourceUrl: 'https://www.dm.at/services/kundenprogramme-services/immerguenstig',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'planned-dauerpreis-not-temporary-offer-source',
    priority: 25,
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle Immerguenstig-Seite ist ein Dauerpreis-/Preisversprechen-Kontext und darf nicht als befristete Aktion in aktive Angebote einlaufen.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'aggregator',
    label: 'Marktguru dm Angebote',
    sourceUrl: 'https://www.marktguru.at/r/dm',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; Aktionsfinder/wogibtswas liefern aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'aggregator',
    label: 'wogibtswas dm Angebote',
    sourceUrl: 'https://www.wogibtswas.at/h/73424-dm',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Zusaetzliche oeffentliche Produkt- und Flugblattquelle fuer aktuelle dm-Angebote.',
  },
  {
    retailerKey: 'pagro',
    retailerName: 'PAGRO',
    channel: 'official-site',
    label: 'PAGRO Angebote',
    sourceUrl: 'https://www.pagro.at/angebote',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-cloudflare-source',
    priority: 10,
    crawlPolicy: {
      categorySeedUrls: [
        'https://www.pagro.at/angebote/90-online-only-sale',
        'https://www.pagro.at/angebote/angebote-buero-schule',
        'https://www.pagro.at/angebote/angebote-basteln-kreativ',
        'https://www.pagro.at/angebote/angebote-spielen',
        'https://www.pagro.at/angebote/angebote-party-schenken',
        'https://www.pagro.at/angebote/angebote-haushalt',
        'https://www.pagro.at/angebote/angebote-gaming',
        'https://www.pagro.at/angebote/angebote-technik',
        'https://www.pagro.at/angebote/angebote-saisonen',
        'https://www.pagro.at/angebote/dauer-mega-packs',
        'https://www.pagro.at/angebote/sale',
      ],
    },
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle PAGRO-Angebotsseite zeigt Produktangebote mit Preisen/Pagination, lokale Node-Fetches erhalten aber Cloudflare-Challenge. Angebotskategorien sind als Seeds dokumentiert und duerfen nicht durch eine generische Aggregator-Abkuerzung ersetzt werden. Erst aktivieren, wenn eine erlaubte stabile HTML/API/PDF-Quelle verfuegbar ist.',
  },
  {
    retailerKey: 'pagro',
    retailerName: 'PAGRO',
    channel: 'official-flyer',
    label: 'PAGRO Flugblatt',
    sourceUrl: 'https://www.pagro.at/cms/flugblatt',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-cloudflare-source',
    priority: 8,
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle PAGRO-Flugblattseite aus der Resource-Matrix. Lokal Cloudflare/403-Risiko; nur mit offiziell direkt erreichbarer PDF-/Asset-Ressource oder manuellem Fixture weiter ausbauen.',
  },
  {
    retailerKey: 'pagro',
    retailerName: 'PAGRO',
    channel: 'aggregator',
    label: 'Aktionsfinder PAGRO & LIBRO Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/pagro-libro/',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/pagro-libro liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. PAGRO bleibt Coverage-kritisch und braucht separate offizielle/legale Source-Entscheidung.',
  },
  {
    retailerKey: 'pagro',
    retailerName: 'PAGRO',
    channel: 'aggregator',
    label: 'Marktguru PAGRO Angebote',
    sourceUrl: 'https://www.marktguru.at/r/pagro',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; Aktionsfinder liefert aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
  {
    retailerKey: 'bipa',
    retailerName: 'BIPA',
    channel: 'official-site',
    label: 'BIPA Aktionen',
    sourceUrl: 'https://www.bipa.at/cp/aktionen',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BIPA-Aktionsseite mit Produktkacheln und Aktionslisten als Primaerquelle.',
  },
  {
    retailerKey: 'bipa',
    retailerName: 'BIPA',
    channel: 'official-site',
    label: 'BIPA Online Only',
    sourceUrl: 'https://www.bipa.at/cp/onlineonly',
    sourceType: 'bipa-official-onlineonly',
    priority: 18,
    crawlPolicy: {
      landingPageOnly: true,
      forcedConditionText: 'Online only',
      customerProgramRequired: false,
      sourceTimeoutMs: 120000,
      freshnessTtlHours: 96,
    },
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BIPA Online-only-Angebotsseite. Aktiviert mit erzwungener Bedingung "Online only", landingPageOnly ohne Detailseiten/Kategorie-Expansion und konservativer Freshness ueber sichtbare BIPA-Aktionsvaliditaet.',
  },
  {
    retailerKey: 'bipa',
    retailerName: 'BIPA',
    channel: 'official-site',
    label: 'BIPA Aktionskategorien erweitert',
    sourceUrl: 'https://www.bipa.at/c/pflege?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis',
    sourceType: 'bipa-official-category-expanded',
    priority: 19,
    crawlPolicy: {
      onlyConfiguredPageUrls: true,
      transport: 'curl',
      sourceTimeoutMs: 120000,
      freshnessTtlHours: 96,
      categorySeedUrls: [
        'https://www.bipa.at/c/haushalt?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis',
        'https://www.bipa.at/c/mund--und-zahnpflege?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis',
        'https://www.bipa.at/c/make-up?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis',
        'https://www.bipa.at/c/haar?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis',
        'https://www.bipa.at/c/baby-und-kind?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis',
        'https://www.bipa.at/c/parfum?limit=100&refine_0=c_pricebadges%3DAktion',
        'https://www.bipa.at/c/tier?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis',
      ],
    },
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BIPA-Aktionskategorien mit Pricebadge-Filtern und limit=100. Nur konfigurierte Kategorie-Seeds, keine Auto-Discovery, damit scoped Crawls begrenzt bleiben.',
  },
  {
    retailerKey: 'bipa',
    retailerName: 'BIPA',
    channel: 'official-site',
    label: 'BIPA Aktionskategorien erweitert Seite 2',
    sourceUrl: 'https://www.bipa.at/c/pflege?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis&start=100',
    sourceType: 'bipa-official-category-expanded-page2',
    priority: 20,
    crawlPolicy: {
      onlyConfiguredPageUrls: true,
      transport: 'curl',
      sourceTimeoutMs: 120000,
      freshnessTtlHours: 96,
      categorySeedUrls: [
        'https://www.bipa.at/c/haushalt?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis&start=100',
        'https://www.bipa.at/c/mund--und-zahnpflege?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis&start=100',
        'https://www.bipa.at/c/make-up?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis&start=100',
        'https://www.bipa.at/c/parfum?limit=100&refine_0=c_pricebadges%3DAktion&start=100',
        'https://www.bipa.at/c/tier?limit=100&refine_0=c_pricebadges%3DAktion%7C1%2B1%20gratis%7Cab%202%20St%C3%BCck%20Aktion%7C2%2B1%20gratis&start=100',
      ],
    },
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BIPA-Aktionskategorien, zweite Ergebnisseite je Kategorie. Nur sechs vorab gepruefte start=100-Seiten, curl-Transport, keine Auto-Discovery und keine weiteren Pagination-Schritte.',
  },
  {
    retailerKey: 'bipa',
    retailerName: 'BIPA',
    channel: 'official-site',
    label: 'BIPA joe Bonusclub',
    sourceUrl: 'https://www.bipa.at/cp/joe-bonusclub',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'planned-club-condition-source',
    priority: 25,
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'joe-/Bonusclubbedingungen muessen getrennt von normalen Angeboten modelliert werden; keine produktive Aktivierung ohne Condition-Gating.',
  },
  {
    retailerKey: 'bipa',
    retailerName: 'BIPA',
    channel: 'aggregator',
    label: 'Aktionsfinder BIPA Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/bipa/',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-unreliable-source',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Deaktiviert: Aktionsfinder /pv/bipa liefert stabil 404 ohne Redirect oder belegte Ersatzstruktur. BIPA hat offizielle Quellen; Aggregator-Fallback derzeit nicht produktiv.',
  },
  {
    retailerKey: 'bipa',
    retailerName: 'BIPA',
    channel: 'aggregator',
    label: 'Marktguru BIPA Angebote',
    sourceUrl: 'https://www.marktguru.at/r/bipa',
    enabled: false,
    latestStatus: 'inactive',
    disabledReason: 'disabled-low-yield',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Deaktiviert: Marktguru lieferte wiederholt 0 brauchbare Offers; BIPA offizielle Quelle und Aktionsfinder liefern aktuell verlaesslicher. Spaeter erneut pruefen.',
  },
];

module.exports = {
  RETAILER_DEFINITIONS,
};
