const RETAILER_DEFINITIONS = [
  {
    retailerKey: 'hofer',
    retailerName: 'Hofer',
    channel: 'aggregator',
    label: 'Aktionsfinder HOFER Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/hofer/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung.',
  },
  {
    retailerKey: 'hofer',
    retailerName: 'Hofer',
    channel: 'official-flyer',
    label: 'HOFER aktuelle Flugblaetter und Broschueren',
    sourceUrl: 'https://www.hofer.at/de/angebote/aktuelle-flugblaetter-und-broschuren.html',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle HOFER-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'hofer',
    retailerName: 'Hofer',
    channel: 'aggregator',
    label: 'Marktguru HOFER Angebote',
    sourceUrl: 'https://www.marktguru.at/r/hofer',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Zweite oeffentliche Aggregator-Quelle fuer aktuelle HOFER-Angebote.',
  },
  {
    retailerKey: 'lidl',
    retailerName: 'Lidl',
    channel: 'aggregator',
    label: 'Aktionsfinder Lidl Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/lidl/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung.',
  },
  {
    retailerKey: 'lidl',
    retailerName: 'Lidl',
    channel: 'official-flyer',
    label: 'Lidl Flugblatt',
    sourceUrl: 'https://www.lidl.at/c/flugblatt/s10012330',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle Lidl-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'lidl',
    retailerName: 'Lidl',
    channel: 'aggregator',
    label: 'Marktguru Lidl Angebote',
    sourceUrl: 'https://www.marktguru.at/r/lidl',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Zweite oeffentliche Aggregator-Quelle fuer aktuelle Lidl-Angebote.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'Spar',
    channel: 'aggregator',
    label: 'Aktionsfinder SPAR Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/spar/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator-Fallback, da die offizielle Seite teils regionale Auswahl und dynamische Strukturen verwendet.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'Spar',
    channel: 'official-flyer',
    label: 'SPAR Aktionen',
    sourceUrl: 'https://www.spar.at/aktionen',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle SPAR-Aktionsseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'spar',
    retailerName: 'Spar',
    channel: 'aggregator',
    label: 'Marktguru SPAR Angebote',
    sourceUrl: 'https://www.marktguru.at/r/spar',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Zweite oeffentliche Aggregator-Quelle fuer aktuelle SPAR-Angebote.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'aggregator',
    label: 'Aktionsfinder BILLA Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/billa/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'official-flyer',
    label: 'BILLA Flugblatt',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/flugblatt',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle BILLA-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'official-site',
    label: 'BILLA Aktionen',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/aktionen',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BILLA-Aktionsseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa',
    retailerName: 'Billa',
    channel: 'aggregator',
    label: 'Marktguru BILLA Angebote',
    sourceUrl: 'https://www.marktguru.at/r/billa',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Zweite oeffentliche Aggregator-Quelle fuer aktuelle BILLA-Angebote.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'aggregator',
    label: 'Aktionsfinder BILLA PLUS Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/billa-plus/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'official-flyer',
    label: 'BILLA PLUS Flugblatt',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/flugblatt',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle BILLA/BILLA PLUS-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'official-site',
    label: 'BILLA PLUS Aktionen',
    sourceUrl: 'https://www.billa.at/unsere-aktionen/aktionen',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle BILLA/BILLA PLUS-Aktionsseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'billa-plus',
    retailerName: 'Billa Plus',
    channel: 'aggregator',
    label: 'Marktguru BILLA PLUS Angebote',
    sourceUrl: 'https://www.marktguru.at/r/billa-plus',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Zweite oeffentliche Aggregator-Quelle fuer aktuelle BILLA PLUS-Angebote.',
  },
  {
    retailerKey: 'adeg',
    retailerName: 'ADEG',
    channel: 'aggregator',
    label: 'Aktionsfinder ADEG Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/adeg/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung.',
  },
  {
    retailerKey: 'adeg',
    retailerName: 'ADEG',
    channel: 'official-flyer',
    label: 'ADEG Flugblatt',
    sourceUrl: 'https://www.adeg.at/flugblatt-aktionen/adeg-flugblatt',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle ADEG-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'adeg',
    retailerName: 'ADEG',
    channel: 'official-site',
    label: 'ADEG Startseite',
    sourceUrl: 'https://www.adeg.at/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle ADEG-Startseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'adeg',
    retailerName: 'ADEG',
    channel: 'aggregator',
    label: 'Marktguru ADEG Aktiv Angebote',
    sourceUrl: 'https://www.marktguru.at/r/adeg-aktiv',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Zweite oeffentliche Aggregator-Quelle fuer aktuelle ADEG-Angebote.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'aggregator',
    label: 'Aktionsfinder PENNY Aktionen',
    sourceUrl: 'https://www.aktionsfinder.at/pv/penny/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: true },
    notes: 'Aggregator fuer breite aktuelle Angebotsabdeckung.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'official-flyer',
    label: 'PENNY Flugblaetter',
    sourceUrl: 'https://www.penny.at/angebote/flugblaetter',
    capabilities: { discoverOffers: true, parseOfferPages: false, parseFlyers: true },
    notes: 'Offizielle PENNY-Flugblattseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'official-site',
    label: 'PENNY Angebote',
    sourceUrl: 'https://www.penny.at/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle PENNY-Startseite mit aktuellen Angeboten als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'penny',
    retailerName: 'PENNY',
    channel: 'aggregator',
    label: 'Marktguru PENNY Angebote',
    sourceUrl: 'https://www.marktguru.at/r/penny',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Zweite oeffentliche Aggregator-Quelle fuer aktuelle PENNY-Angebote.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'official-site',
    label: 'dm Startseite',
    sourceUrl: 'https://www.dm.at/',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Offizielle dm-Startseite als zusaetzliche Primaerquelle.',
  },
  {
    retailerKey: 'dm',
    retailerName: 'dm',
    channel: 'aggregator',
    label: 'Marktguru dm Angebote',
    sourceUrl: 'https://www.marktguru.at/r/dm',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Oeffentliche Aggregator-Quelle fuer aktuelle dm-Angebote.',
  },
  {
    retailerKey: 'pagro',
    retailerName: 'PAGRO',
    channel: 'aggregator',
    label: 'Marktguru PAGRO Angebote',
    sourceUrl: 'https://www.marktguru.at/r/pagro',
    capabilities: { discoverOffers: true, parseOfferPages: true, parseFlyers: false },
    notes: 'Oeffentliche Aggregator-Quelle fuer aktuelle PAGRO-Angebote.',
  },
];

module.exports = {
  RETAILER_DEFINITIONS,
};
